<?php
// $Id$

/**
 * @file
 *
 *
 *
 *
 */

/**
 * Implements hook_help().
 */
function my_theming_help($path, $arg) {
  if ($path == 'admin/help#my_theming') {
    return t('Theming module.');
  }
}

/**
 * Implements hook_menu().
 */
function my_theming_menu() {
  $items['theming'] = array(
      'title' => 'Theming',
      'page callback' => 'theming_page',
      'access callback' => TRUE,
    );

  return $items;
}

/**
 * Page callback for /theming.
 */
function theming_page() {
  $text_one = 'What the hell';
  $text_two = array(
    array('data' => 'first'),
    array('data' => 'second'),
    array('data' => 'third'));
  $text_three[] = array(
    array('data' => 'apple'),
    array('data' => 'orange'),
    array('data' => 'pineapple'));
  $text_four = array(
      '#title' => 'Example fieldset',
      '#children' => 'Hello!',
    );

  $function_one = theme('theming_template',
    array(
    '#theme' => 'theming_template',
    '#type' => 'markup',
    '#text_one' => $text_one,
    ));
  $function_two = theme('item_list',
    array('items' => $text_two, 'type' => 'ol'));
  $function_three = theme('table',
    array('header' => $text_two, 'rows' => $text_three));
  $function_four = theme('fieldset',
    array('element' => $text_four));
  $function_five = theme('image_style',
    array('style_name' => 'form-preview', 'path' => 'public://Godfather.jpg'));
  return $function_one . $function_two . $function_three . $function_four . $function_five;
}

/**
 * Implements hook_theme().
 */
function my_theming_theme($existing, $type, $theme, $path) {
  return array(
    'theming_function' => array(
      'variables' => array(
        'text_one' => NULL,
      ),
    ),
    'theming_template' => array(
      'variables' => array(
        'text_one' => NULL,
      ),
      'template' => 'my_theming',
    ),
  );
}

/**
 * Theme function.
 */
function theme_theming_function($variables) {
  $output = "<h2><strong>" . $variables['text_one'] . "</strong></h2>";
  return $output;
}
