<?php
// $Id$

/**
 * @file
 *
 *
 *
 *
 */

/**
 * Implements hook_help().
 */
function my_form_help($path, $arg) {
  if ($path == 'admin/help#my_form') {
    return t('Form module');
  }
}

/**
 * Implements hook_menu().
 */
function my_form_menu() {
  $items['contacts'] = array(
      'title' => 'Contacts',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('my_form_form'),
      'access callback' => TRUE,
    );

  return $items;
}

/**
 * Page callback for /contacts.
 */
function contact_page() {
  return my_form_form();
}

/**
 * Implements hook_form().
 */
function my_form_form($form, &$form_state) {

  $form = array();

  $form['username'] = array(
      '#type' => 'textfield',
      '#title' => t('Your username'),
      '#size' => 10,
      '#maxlength' => 10,
      '#required' => TRUE,
    );

  $form['email'] = array(
      '#type' => 'textfield',
      '#title' => t('Your E-mail'),
      '#size' => 15,
      '#maxlength' => 25,
      '#required' => TRUE,
    );

  $form['phone'] = array(
      '#type' => 'textfield',
      '#title' => 'Your phone number',
      '#size' => 15,
      '#maxlength' => 15,
    );

  $form['gender'] = array(
      '#type' => 'radios',
      '#title' => t('Male or female?'),
      '#options' => array(
          t('Male'),
          t('Female'),
        ),
      '#required'=>TRUE,
      '#default_value' => 0,
    );

  $form['country'] = array(
      '#type' => 'select',
      '#title' => t('Country'),
      '#options' => array(
          t('Ukraine'),
          t('USA'),
          t('Russia'),
        ),
    );

  $form['message'] = array(
      '#type' => 'textarea',
      '#title' => t('Message'),
      '#required' => TRUE,
    );

  $agreement = array(
      '#title' => t('License agreement'),
      '#children' => t('Some text of agreement'),
    );

  $fieldset = theme('fieldset', array('element' => $agreement));

  $form['agreement'] = array(
      '#markup' => $fieldset,
    );

  $form['terms'] = array(
      '#type' => 'checkbox',
      '#title' => t('I agree'),
      '#required' => TRUE,
    );

  $form['submit_button'] = array(
      '#type' => 'submit',
      '#value' => t('Push me baby!'),
    );

  return $form;
}

/**
 * Implements hook_form_alter().
 */
function my_form_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'my_form_form') {
    $form['#validate'][] = 'my_form_form_validate';
  }
}

/**
 * Implements hook_form_validate().
 */
function my_form_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('Enter correct email please'));
  }

  if (!preg_match('/^[0-9\-\+]{9,15}$/',$form_state['values']['phone'])) {
  form_set_error('phone', t('Enter correct phone number'));
  }

}

/**
 * Implements hook_form_submit().
 */
function my_from_form_submit($form, &$form_state) {
  drupal_set_message('');
}
