<?php
// $Id$

/**
 * @file
 *
 *
 *
 *
 */

/**
 * Implements hook_help().
 */
function my_database_help($path, $arg) {
  if ($path == 'admin/help#my_database') {
    return t('Database module');
  }
}

/**
 * Implements hook_menu().
 */
function my_database_menu() {
  $items['database'] = array(
      'title' => 'Database',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('my_database_form'),
      'access callback' => TRUE,
    );
  $items['articles'] = array(
      'title' => 'Articles',
      'page callback' => 'articles_page',
      'access callback' => TRUE,
    );
  $items['editArticle'] = array(
      'title' => 'Edit',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('edit_article_form'),
      'access callback' => TRUE,
    );

  return $items;
}

/**
 * Page callback for /articles.
 */
function articles_page() {
  //$results = db_query("SELECT * FROM {custom_table}");

  $query = db_select('custom_table', 'ct');
  $query
    ->fields('ct', array('id', 'number', 'teaser', 'text'))
    ->orderBy('ct.id');
  $results = $query->execute();

  $header = array(t('ID'), t('Number'), t('Teaser'), t('Text'), t('Action'));
  $rows = array();

  foreach($results as $result) {
    $rows[] = array(
        $result->id,
        $result->number,
        $result->teaser,
        $result->text,
        "<a href='./editForm&amp;id='".$result->id.">Edit</a>",
      );
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Page callback for /editArticle.
 */
function edit_article_form($form, &$form_state) {
  $form = array();
}

/**
 * Implements hook_form().
 */
function my_database_form($form, &$form_state) {
  $form = array();

  $form['number'] = array(
      '#type' => 'textfield',
      '#title' => t('Number'),
      '#required' => TRUE,
    );

  $form['teaser'] = array(
      '#type' => 'textfield',
      '#title' => t('Teaser'),
      '#maxlength' => 150,
      '#required' => TRUE,
    );

  $form['text'] = array(
      '#type' => 'textarea',
      '#title' => t('Text'),
      '#required' => TRUE,
    );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Submit',
    );

  return $form;
}

/**
 * Validation for my_database_form().
 */
function my_database_form_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['number'])) {
    form_set_error('number', t('Not a number'));
    return false;
  }

  return true;
}

/**
 * Submit for my_database_form().
 */
function my_database_form_submit($form, &$form_state) {
  $fe_id = db_insert('custom_table')
    ->fields(array(
      'number' => $form_state['values']['number'],
      'teaser' => $form_state['values']['teaser'],
      'text' => $form_state['values']['teaser']
    ))
    ->execute();

  drupal_set_message(t('Your form has been submitted'));
}
